name: Test Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  test-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Check for new version
      - name: Verify new version
        id: version_check
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NPM_VERSION=$(npm view react-i18n-query@${CURRENT_VERSION} version || echo 'not_found')
          if [ "$NPM_VERSION" == "$CURRENT_VERSION" ]; then
            echo "This version ($CURRENT_VERSION) already exists on npm."
            echo "::set-output name=should_publish::false"
          else
            echo "New version detected: $CURRENT_VERSION"
            echo "::set-output name=should_publish::true"
          fi

      # Step 5: Build the package
      - name: Build package
        run: npm run build
        if: steps.version_check.outputs.should_publish == 'true'

      # Step 6: Test npm publish (Dry Run)
      - name: Test npm publish (Dry Run)
        run: npm publish --dry-run
        if: steps.version_check.outputs.should_publish == 'true'

      # Step 7: Prevent Workflow Loops
      - name: Stop workflow loop
        if: github.actor == 'github-actions[bot]'
        run: echo "Stopping workflow triggered by GitHub Actions itself."
