name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
    # Prevents retriggering the workflow on tag pushes
    tags-ignore:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      DRY_RUN: true # Set this to `true` for testing mode

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          token: ${{ secrets.NPM_TOKEN }}
          always-auth: true

      - name: Verify npm auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Lint and Build Package
        run: |
          npm run lint
          npm run build

      - name: Check and Publish Package
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")

          echo "Current version: $CURRENT_VERSION"
          echo "Package name: $PACKAGE_NAME"

          # Check if the current version is already published
          if npm view "$PACKAGE_NAME@$CURRENT_VERSION" > /dev/null 2>&1; then
            echo "Version $CURRENT_VERSION already exists. Skipping publish."
            exit 0
          else
            echo "Publishing new version $CURRENT_VERSION (dry-run: $DRY_RUN)."

            # Dry-run or real publish based on DRY_RUN variable
            if [ "$DRY_RUN" == "true" ]; then
              # Dry-run publish to test the workflow without actually publishing
              npm publish --access public --dry-run || PUBLISH_EXIT_CODE=$?
            else
              # Real publish
              npm publish --access public || PUBLISH_EXIT_CODE=$?
            fi

            # If publish fails, handle the error
            if [ -n "$PUBLISH_EXIT_CODE" ] && [ "$PUBLISH_EXIT_CODE" -eq 1 ]; then
              echo "Publish returned exit code 1, indicating a potential issue."
              exit 0
            fi
          fi

          # Only create and push a tag if DRY_RUN is not true
          if [ "$DRY_RUN" != "true" ]; then
            # Check if tag already exists to avoid duplication
            if ! git tag --list | grep -q "v$CURRENT_VERSION"; then
              echo "Creating and pushing tag v$CURRENT_VERSION."
              git tag "v$CURRENT_VERSION"
              git push origin "v$CURRENT_VERSION"
            else
              echo "Tag v$CURRENT_VERSION already exists. Skipping tag creation."
            fi
          else
            echo "Dry-run mode active, skipping tag creation."
          fi
