name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  # Optionally, trigger for tags prefixed with 'v'
  # tags:
  #   - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint and Build Package
        run: |
          npm run lint
          npm run build

      - name: Check and Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")

          # Check if the current version is already published
          if npm view "$PACKAGE_NAME@$CURRENT_VERSION" > /dev/null 2>&1; then
            echo "Version $CURRENT_VERSION already exists. Skipping publish."
          else
            echo "Publishing new version $CURRENT_VERSION."
            npm publish --access public

            # Create and push a new tag for the version
            git tag "v$CURRENT_VERSION"
            git push origin "v$CURRENT_VERSION"
          fi
