name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and Cache Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint and Build Package
        run: |
          npm run lint
          npm run build

      - name: Check Package Version
        id: version_check
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          if npm view "$PACKAGE_NAME@$CURRENT_VERSION" > /dev/null 2>&1; then
            echo "version-exists=true" >> $GITHUB_OUTPUT
          else
            echo "version-exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish Package
        if: steps.version_check.outputs.version-exists == 'false'
        run: |
          echo "Publishing new version $CURRENT_VERSION."
          npm publish --access public
          git tag "v$CURRENT_VERSION"
          git push origin "v$CURRENT_VERSION"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
