name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Check for new version
      - name: Verify new version
        id: version_check
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NPM_VERSION=$(npm view react-i18n-query@${CURRENT_VERSION} version || echo 'not_found')
          if [ "$NPM_VERSION" == "$CURRENT_VERSION" ]; then
            echo "should_publish=false" >> $GITHUB_ENV
          else
            echo "New version detected: $CURRENT_VERSION"
            echo "should_publish=true" >> $GITHUB_ENV
          fi

      # Step 5: Build the package (only if a new version is detected)
      - name: Build package
        run: npm run build
        if: env.should_publish == 'true'

      # Step 6: Publish to npm (only if a new version is detected)
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NPM_VERSION=$(npm view react-i18n-query@${CURRENT_VERSION} version || echo 'not_found')
          if [ "$NPM_VERSION" == "$CURRENT_VERSION" ]; then
            echo "Version $CURRENT_VERSION already exists on npm, skipping publish."
            exit 0
          fi
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: env.should_publish == 'true'

      # Step 7: Avoid Infinite Loop by skipping bot commits
      - name: Skip GitHub Actions bot commits
        if: github.actor == 'github-actions[bot]'
        run: echo "Commit by GitHub Actions bot, skipping publish."
