name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
    # Prevents retriggering the workflow on tag pushes
    tags-ignore:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          token: ${{ secrets.NPM_TOKEN }}
          always-auth: true

      - name: Verify npm auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Lint and Build Package
        run: |
          npm run lint
          npm run build

      - name: Check and Publish Package (Dry Run)
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")

          echo "Current version: $CURRENT_VERSION"
          echo "Package name: $PACKAGE_NAME"

          # Check if the current version is already published
          if npm view "$PACKAGE_NAME@$CURRENT_VERSION" > /dev/null 2>&1; then
            echo "Version $CURRENT_VERSION already exists. Skipping publish."
            exit 0
          else
            echo "Publishing new version $CURRENT_VERSION (dry-run)."

            # Dry-run publish to test the workflow without actually publishing
            npm publish --access public --dry-run || PUBLISH_EXIT_CODE=$?

            # If dry-run publish fails, handle the error
            if [ -n "$PUBLISH_EXIT_CODE" ] && [ "$PUBLISH_EXIT_CODE" -eq 1 ]; then
              echo "Dry-run publish returned exit code 1, indicating a potential issue."
              exit 0
            fi
          fi

          # Check if tag already exists to avoid duplication
          if ! git tag --list | grep -q "v$CURRENT_VERSION"; then
            echo "Creating and pushing tag v$CURRENT_VERSION."
            git tag "v$CURRENT_VERSION"

            # Add [skip ci] to commit message to prevent workflow from triggering again
            git push origin "v$CURRENT_VERSION" -o ci.skip
          else
            echo "Tag v$CURRENT_VERSION already exists. Skipping tag creation."
          fi
